=== SashaMGuerra/2021_LMGSI_IMG/ud04/ex-2020/catalogo.xsd
<?xml version="1.0"?>
<!-- Autor: Sasha. Fecha de creaciÃ³n: 25/2/2021 -->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xs:attribute name="tamanyo">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="GB"/>
                <xs:enumeration value="MB"/>
                <xs:enumeration value="TB"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    
    <xs:element name="catalogo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="portatil" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ref">
                                <xs:simpleType>
                                    <xs:restriction base="xs:ID">
                                        <xs:pattern value="[A-Z]{2}[0-9]{5}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="nombre">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="20"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="fabricante">
                                <xs:complexType>
                                    <xs:attribute name="nombre">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="HP"/>
                                                <xs:enumeration value="Lenovo"/>
                                                <xs:enumeration value="Apple"/>
                                                <xs:enumeration value="Asus"/>
                                            </xs:restriction> 
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="procesador">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombreproc" type="xs:string"/>
                                        <xs:element name="cache">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:integer">
                                                        <xs:attribute ref="tamanyo"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="numero" type="xs:byte"/>
                                        <xs:element name="vel" type="xs:decimal"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="ram">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="memoria">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:integer">
                                                        <xs:attribute ref="tamanyo"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="tipo">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="DDR3"/>
                                                    <xs:enumeration value="DDR4"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="disco">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="tamanyodisco">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute ref="tamanyo"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="tipodisco">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="SSD"/>
                                                    <xs:enumeration value="HDD"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="pantalla">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="dimension" type="xs:float"/>
                                        <xs:element name="resolucion">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[1-9]*[x][1-9]*"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="max_resolucion" minOccurs="0">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[1-9]*[x][1-9]*"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="grafica" minOccurs="0" type="xs:string"/>
                            <xs:element name="foto" minOccurs="0" maxOccurs="unbounded">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-z]*[.][a-z]{3}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SashaMGuerra/2021_LMGSI_IMG/ud04/ex-2020/catalogo_schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Autor: Sasha. Fecha de creaciÃ³n: 25/2/2021 -->

<catalogo
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='catalogo.xsd'>
    
    <portatil>
        <ref>HP10219</ref>
        <nombre>DA0204NS</nombre>
        <fabricante nombre="HP"/>
        <procesador>
            <nombreproc>I3-7020U</nombreproc>
            <cache tamanyo="GB">500</cache>
            <numero>1</numero>
            <vel>1</vel>
        </procesador>
        <ram>
            <memoria tamanyo="TB">1</memoria>
            <tipo>DDR4</tipo>
        </ram>
        <disco>
            <tamanyodisco tamanyo="GB">256</tamanyodisco>
            <tipodisco>SSD</tipodisco>
        </disco>
        <pantalla>
            <dimension>15.6</dimension>
            <resolucion>1266x768</resolucion>
            <max_resolucion>1366x768</max_resolucion>
        </pantalla>
    </portatil>
    <portatil>
        <ref>LV14583</ref>
        <nombre>IDEAPAD</nombre>
        <fabricante nombre="Lenovo"/>
        <procesador>
            <nombreproc>I3-8145U</nombreproc>
            <cache tamanyo="TB">1</cache>
            <numero>1</numero>
            <vel>1</vel>
        </procesador>
        <ram>
            <memoria>16</memoria>
            <tipo>DDR4</tipo>
        </ram>
        <disco>
            <tamanyodisco tamanyo="MB">51200</tamanyodisco>
            <tipodisco>HDD</tipodisco>
        </disco>
        <pantalla>
            <dimension>15.6</dimension>
            <resolucion>1266x768</resolucion>
            <max_resolucion>1366x768</max_resolucion>
        </pantalla>
        <grafica>Intel UHD Graphics 620</grafica>
        <foto>portatillenovo.jpg</foto>
        <foto>portatillenovo.png</foto>
    </portatil>
</catalogo>
