=== SashaMGuerra/2021_LMGSI_IMG/ud04/practicas/02_2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT continente (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT capital (#PCDATA)>
<!ELEMENT lugar (continente, capital)>
<!ELEMENT tabla (lugar+)>
<!ATTLIST lugar pais CDATA #REQUIRED>

=== SashaMGuerra/2021_LMGSI_IMG/ud04/02_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tabla SYSTEM '02_2.dtd'>
<tabla>
    <lugar pais="Alemania">
        <continente>Europa</continente>
        <capital>Berlín</capital>
    </lugar>
    <lugar pais="Argentina">
        <continente>América</continente>
        <capital>Buenos Aires</capital>
    </lugar>
    <lugar pais="Bahamas">
        <continente>América</continente>
        <capital>Nassau</capital>
    </lugar>
    <lugar pais="Afganistan">
        <continente>Asia</continente>
        <capital>Kabul</capital>
    </lugar>
    <lugar pais="Arabia Saudita">
        <continente>Asia</continente>
        <capital>Riad</capital>
    </lugar>
</tabla>
