<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tabla [
    <!ELEMENT descripcion (#PCDATA)>
    <!ELEMENT dia (#PCDATA)>
    <!ELEMENT mes (#PCDATA)>
    <!ELEMENT anyo (#PCDATA)>
    <!ELEMENT fecha (dia, mes, anyo)>
    <!ELEMENT hecho (descripcion, fecha)>
    <!ELEMENT tabla (hecho+)>
]>
<tabla>
    <hecho>
        <descripcion>Se funda Youtube</descripcion>
        <fecha>
            <dia>15</dia>
            <mes>2</mes>
            <anyo>2005</anyo>
        </fecha>
    </hecho>
    <hecho>
        <descripcion>Se funda Google</descripcion>
        <fecha>
            <dia>4</dia>
            <mes>9</mes>
            <anyo>1998</anyo>
        </fecha>
    </hecho>
    <hecho>
        <descripcion>Se funda Facebook</descripcion>
        <fecha>
            <dia>4</dia>
            <mes>2</mes>
            <anyo>2004</anyo>
        </fecha>
    </hecho>
</tabla>
