=== SashaMGuerra/2021_LMGSI_IMG/ud04/practicas/05.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT contact_n (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT zip (#PCDATA)>
<!ELEMENT address (city, state, zip)>
<!ELEMENT employee (firstname, lastname, contact_n?, email+, address)>
<!ELEMENT company (employee+)>

=== SashaMGuerra/2021_LMGSI_IMG/ud04/05.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE company SYSTEM "05.dtd">
<company>
    <employee>
        <firstname>Juan</firstname>
        <lastname>SÃ¡nchez</lastname>
        <contact_n>123456789</contact_n>
        <email>juansanchez@company.com</email>
        <address>
            <city>Bangalore</city>
            <state>Karnataka</state>
            <zip>560212</zip>
        </address>
    </employee>
</company>
