=== SashaMGuerra/2021_LMGSI_IMG/ud04/EX02_02210309_MISABELMTNEZGUERRA/mapaestelar.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT constelaciones (constelacion)*>
<!ATTLIST constelaciones
    xsi:noNamespaceSchemaLocation CDATA #IMPLIED
    xmlns:xsi CDATA #IMPLIED
  >


<!ELEMENT constelacion (nombreespanyol,superficie,estrellas,objetos,colindantes,observacion)>
<!ATTLIST constelacion
    nombreLatin CDATA #IMPLIED
  >

<!ELEMENT nombreespanyol (#PCDATA)>
<!ELEMENT superficie (#PCDATA)>

<!ELEMENT estrellas (asterismo,masBrillante,estrella*)>
<!ATTLIST estrellas
    numestrellas CDATA #IMPLIED
  >

<!ELEMENT asterismo (#PCDATA)>
<!ELEMENT masBrillante (#PCDATA)>
<!ATTLIST masBrillante
    luminosidad CDATA #IMPLIED
  >
<!ELEMENT estrella (nombrestrella,constorigen,distancia,luminosidad,temperatura,masa)>

<!ELEMENT nombrestrella (#PCDATA)>
<!ELEMENT constorigen (#PCDATA)>
<!ELEMENT distancia (#PCDATA)>
<!ELEMENT luminosidad (#PCDATA)>
<!ELEMENT temperatura (#PCDATA)>
<!ELEMENT masa (#PCDATA)>

<!ELEMENT objetos (cumulos,nebulosas,galaxias,cuasares,lluviameteros*)>

<!ELEMENT cumulos (#PCDATA)>
<!ELEMENT nebulosas (#PCDATA)>
<!ELEMENT galaxias (#PCDATA)>
<!ELEMENT cuasares (#PCDATA)>
<!ELEMENT lluviameteoros (#PCDATA)>

<!ELEMENT colindantes (nombre)*>
<!ELEMENT nombre (#PCDATA)>

<!ELEMENT observacion (hemisferio,mes,hora)>

<!ELEMENT hemisferio (#PCDATA)>

<!ELEMENT mes (#PCDATA)>

<!ELEMENT hora (#PCDATA)>

=== SashaMGuerra/2021_LMGSI_IMG/ud04/EX02_02210309_MISABELMTNEZGUERRA/mapaestelar.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE constelaciones SYSTEM "mapaestelar.dtd">

<constelaciones
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='mapaestelar.xsd'>
    <constelacion nombreLatin="ursamaior">
        <nombreespanyol>Osa Mayor</nombreespanyol>
        <superficie>1279.7</superficie>
        <estrellas numestrellas="439">
            <asterismo>177</asterismo>
            <masBrillante luminosidad="108">Alioth</masBrillante>
            <estrella>
                <nombrestrella>Alioth</nombrestrella>
                <constorigen>Osa Mayor</constorigen>
                <distancia>81</distancia>
                <luminosidad>108</luminosidad>
                <temperatura>9400</temperatura>
                <masa>3</masa>
            </estrella>
        </estrellas>
        <objetos>
            <cumulos>false</cumulos>
            <nebulosas>true</nebulosas>
            <galaxias>true</galaxias>
            <cuasares>false</cuasares>
        </objetos>
        <colindantes>
            <nombre>Bootes</nombre>
            <nombre>Camelopardalis</nombre>
            <nombre>Canes Venatici</nombre>
            <nombre>Draco</nombre>
            <nombre>Leo</nombre>
            <nombre>Leo Minor</nombre>
            <nombre>Lynx</nombre>
        </colindantes>
        <observacion>
            <hemisferio>norte</hemisferio>
            <mes>2</mes>
            <hora>12:12:12</hora>
        </observacion>
    </constelacion>
</constelaciones>
