=== SashaMGuerra/2021_LMGSI_IMG/ud04/schema/10-Schema.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xs:element name="horario">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="modulos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="modulo" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="codM">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:ID">
                                                        <xs:enumeration value="EDD"/>
                                                        <xs:enumeration value="LMGSI"/>
                                                        <xs:enumeration value="PROG"/>
                                                        <xs:enumeration value="BBDD"/>
                                                        <xs:enumeration value="FOL"/>
                                                        <xs:enumeration value="SINF"/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="profesores">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="profesor" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="codP">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:ID">
                                                        <xs:pattern value="[A-Z]{3}"/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="imparte">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="asignatura" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="codM" type="xs:IDREF"/>
                                    <xs:attribute name="codProfesor" type="xs:IDREF"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="grupo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="hora" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="dia_sem" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="dia">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:string">
                                                                    <xs:enumeration value="lunes"/>
                                                                    <xs:enumeration value="martes"/>
                                                                    <xs:enumeration value="miercoles"/>
                                                                    <xs:enumeration value="jueves"/>
                                                                    <xs:enumeration value="viernes"/>
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:attribute>
                                                        <xs:attribute name="num">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:byte">
                                                                    <xs:enumeration value="1"/>
                                                                    <xs:enumeration value="2"/>
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:attribute>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="entrada" type="xs:time"/>
                                    <xs:attribute name="salida" type="xs:time"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="idgrupo">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="[A-Z]{3}[0-9]"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="codT" type="xs:IDREF"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="curso"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== SashaMGuerra/2021_LMGSI_IMG/ud04/schema/10-Schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Autor: Sasha. Fecha de creación: 18/2/2021 -->

<horario curso="DAW1"
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='10-Schema.xsd'>
    
    <modulos>
        <modulo codM="EDD">Entornos de Desarrollo</modulo>
        <modulo codM="LMGSI">Lenguaje de Marcas y Sistemas Informáticos</modulo>
    </modulos>
    <profesores>
        <profesor codP="MUP">Marcos Unzueta Puente</profesor>
        <profesor codP="ARN">Amor Rodríguez Navarro</profesor>
        <profesor codP="HRO">Hermelinda Ramos Osorio</profesor>
    </profesores>
    <imparte>
        <asignatura codM="EDD" codProfesor="MUP"/>
        <asignatura codM="LMGSI" codProfesor="ARN"/>
    </imparte>
    <grupo codT="MUP" idgrupo="DAW1">
        <hora entrada="08:30:00" salida="09:20:00">
            <dia_sem dia="lunes" num="1">EDD</dia_sem>
        </hora>
        <hora entrada="12:15:00" salida="13:55:00">
            <dia_sem dia="martes" num="2">LMGSI</dia_sem>
        </hora>
    </grupo>
</horario>
