=== SashaMGuerra/2021_LMGSI_IMG/ud04/Pruebas/Modelo.xsd
<?xml version="1.0"?>
<!-- Autor: Sasha. Fecha de creación: 11/2/2021.
    Validación de elementos simples -->
<!-- Fecha de modificación: -->
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="modelo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="curso">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="1"/>
                            <xs:maxInclusive value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="ciclo">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="DAW"/>
                            <xs:enumeration value="ASIR"/>
                            <xs:enumeration value="DAM"/>
                            <xs:enumeration value="SMR"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="nombreciclo">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="3"/>
                            <xs:maxLength value="100"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="cod_postal">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:pattern value="[0-9]{5}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="comentario">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:whiteSpace value="collapse"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="temperatura">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:totalDigits value="5"/>
                            <xs:fractionDigits value="2"/>
                            <xs:minInclusive value="-30"/>
                            <xs:maxInclusive value="50"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="asignatura">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="codigoasignatura">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="BBDD|LMGSI|PROG|SINF|EDD"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="nombreasignatura">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-ZÑÁÉÍÓÚÜ]([a-zA-Z ñÑáÁéÉíÍóÓúÚüÜ])*"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="profesor">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="codP">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:pattern value="[A-Z]{3}"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="modulo" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>       
</xs:schema>

=== SashaMGuerra/2021_LMGSI_IMG/ud04/Pruebas/Modelo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<modelo
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='Modelo.xsd'>
    <ejemplo atributo="at">nombrerestringido</ejemplo>
    <curso>1</curso>
    <ciclo>DAW</ciclo>
    <nombreciclo>Desarrollo de Aplicaciones Web</nombreciclo>
    <cod_postal>49600</cod_postal>
    <comentario>FP Superior de DAW, primer curso</comentario>
    <temperatura>20</temperatura>
    <asignatura>
        <codigoasignatura>LMGSI</codigoasignatura>
        <nombreasignatura>Lenguaje de Marcas</nombreasignatura>
    </asignatura>
    <profesor codP="ARN" modulo="LMGSI">Amor Rodr√≠guez</profesor>

</modelo>
