=== SashaMGuerra/2021_LMGSI_IMG/ud04/01_2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT remitente (#PCDATA)>
<!ELEMENT destinatario (#PCDATA)>
<!ELEMENT asunto (#PCDATA)>
<!ELEMENT mensaje (#PCDATA)>
<!ELEMENT fecha EMPTY>
<!ELEMENT fichero (#PCDATA)>
<!ELEMENT mail (remitente, destinatario+, fecha, asunto?, mensaje?, fichero*)>
<!ATTLIST fecha dia CDATA #REQUIRED mes CDATA #REQUIRED anyo CDATA #REQUIRED>
<!ATTLIST fichero tipo CDATA #IMPLIED>

=== SashaMGuerra/2021_LMGSI_IMG/ud04/practicas/01_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mail SYSTEM '01_2.dtd'>
<mail>
    <remitente>remitente@correo.com</remitente>
    <destinatario>destinatario1@gmail.com</destinatario>
    <destinatario>destintatario2@gmail.com</destinatario>
    <fecha dia="28" mes="01" anyo="2021"/>
    <asunto>Asunto</asunto>
    <mensaje>Cuerpo del mensaje</mensaje>
    <fichero tipo="application/pdf">informe.pdf</fichero>
    <fichero tipo="image/jpeg">foto.jpg</fichero>
</mail>
