=== SashaMGuerra/2021_LMGSI_IMG/ud04/06-Schema.xsd
<?xml version="1.0"?>
<!-- Autor: Sasha. Fecha de creaciÃ³n: 18/2/2021 -->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="lenguajes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="lenguaje" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="codigo" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SashaMGuerra/2021_LMGSI_IMG/ud04/schema/06-Schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Autor: Sasha. Fecha de creaciÃ³n: 18/2/2021 -->
<lenguajes
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='06-Schema.xsd'>
    
    <lenguaje>
        <nombre>HTML</nombre>
        <codigo>
            <![CDATA[
                <h2>Ejemplo de HTML</h2>
                <p>Hola mundo</p>
            ]]>
        </codigo>
    </lenguaje>
    <lenguaje>
        <nombre>Java</nombre>
        <codigo>
            <![CDATA[
                System.out.println("Prueba de Java");
            ]]>
        </codigo>
    </lenguaje>
    <lenguaje>
        <nombre>SQL</nombre>
        <codigo>
            <![CDATA[
                select nombre, apellidos
                from alumnos
                where provincia="Zamora"
            ]]>
        </codigo>
    </lenguaje>
</lenguajes>
