=== SashaMGuerra/2021_LMGSI_IMG/ud04/06.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT lenguajes (lenguaje+)>
<!ELEMENT lenguaje (titulo, codigo)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT codigo (#PCDATA)>

=== SashaMGuerra/2021_LMGSI_IMG/ud04/practicas/06.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="06.css"?>
<!-- Autor: Sasha. Fecha de creaciÃ³n: 18/2/2021 -->
<!DOCTYPE lenguajes SYSTEM "06.dtd">
<lenguajes>
    <lenguaje>
        <titulo>HTML</titulo>
        <codigo>
            <![CDATA[
                <h2>Ejemplo de HTML</h2>
                <p>Hola mundo</p>
            ]]>
        </codigo>
    </lenguaje>
    <lenguaje>
        <titulo>Java</titulo>
        <codigo>
            <![CDATA[
                System.out.println("Prueba de Java");
            ]]>
        </codigo>
    </lenguaje>
    <lenguaje>
        <titulo>SQL</titulo>
        <codigo>
            <![CDATA[
                select nombre, apellidos
                from alumnos
                where provincia="Zamora"
            ]]>
        </codigo>
    </lenguaje>
</lenguajes>
