<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mail[ <!-- DTD interno-->
    <!ELEMENT remitente (#PCDATA)>
    <!ELEMENT destinatario (#PCDATA)>
    <!ELEMENT dia (#PCDATA)>
    <!ELEMENT mes (#PCDATA)>
    <!ELEMENT anyo (#PCDATA)>
    <!ELEMENT asunto (#PCDATA)>
    <!ELEMENT mensaje (#PCDATA)>
    <!ELEMENT n_fichero (#PCDATA)>
    <!ELEMENT tipo (#PCDATA)>
    <!ELEMENT fecha (dia, mes, anyo)>
    <!ELEMENT fichero (n_fichero, tipo)>
    <!ELEMENT mail (remitente, destinatario+, fecha, asunto?, mensaje?, fichero*)>
]>
<mail>
    <remitente>remitente@correo.com</remitente>
    <destinatario>ambrosio@gmail.com</destinatario>
    <destinatario>meli@gmail.com</destinatario>
    <fecha>
        <dia>26</dia>
        <mes>01</mes>
        <anyo>2021</anyo>
    </fecha>
    <asunto>Prueba de mensaje</asunto>
    <mensaje/> <!-- Autocierre pues no contiene nada-->
    <fichero>
        <n_fichero>informe.pdf</n_fichero>
        <tipo>application/pdf</tipo>
    </fichero>
    <fichero>
        <n_fichero>foto.jpg</n_fichero>
        <tipo>image/jpg</tipo>
    </fichero>
</mail>